import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

const notes =
  'Two settings could be saved in combinations this gateway will not start ' +
  'with, and the forms now catch both before you save. ' +
  'Share Stale Seconds accepted any value, but DATUM allows at most 150. ' +
  'Protocol Timeout has to be at least Work Update Seconds plus 5, and the two ' +
  'live in different Config actions, so a pair that was fine when you saved it ' +
  'could be broken later from the other form. Neither form knew about the ' +
  'other; both now check the pair. ' +
  'If you have not changed either setting, nothing here affects you. ' +
  'The service description no longer says regtest only, which stopped being ' +
  'true when chain selection landed.'

export const current = VersionInfo.of({
  version: '1.0.0:28',
  releaseNotes: {
    en_US: notes,
    es_ES: notes,
    de_DE: notes,
    pl_PL: notes,
    fr_FR: notes,
  },
  migrations: {
    // Nothing to migrate. The store gained a `config` object and an
    // `adminPassword`, and every field carries a `.catch()` default, so an
    // existing store.json reads as all-unset and the gateway keeps its current
    // behaviour. Unset means the key is not written at all, which is how a
    // setting nobody has touched still gets DATUM's own default rather than
    // one we chose on their behalf.
    //
    // The dashboard password is generated by `seedFiles` on every init when the
    // field is absent, so an existing install picks one up on this update and
    // the admin pages work without the user doing anything. The Dashboard
    // Password action is where they read it. Someone who clears it deliberately
    // keeps it cleared: an empty string is a decision, and only an absent field
    // is filled.
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
