import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

const notes =
  'The gateway now has the same settings as the official Datum Gateway service, grouped the ' +
  'same way: six Config actions for Bitcoind, Stratum, Mining, API, Logger and DATUM Pool. ' +
  'Anything you leave blank keeps the gateway’s own default. ' +
  'The service page also shows how many miners are connected and their estimated hashrate, ' +
  'as the official service does. ' +
  'The dashboard’s admin pages are on: they list each connected miner with its share counts ' +
  'and hashrate, and were previously unreachable. The password is created for you on install ' +
  'and shown in the new Dashboard Password action. ' +
  'This service now follows whichever chain your node is on, rather than assuming a private ' +
  'chain, so it works on the public BLAKE2b test network. ' +
  'Compatibility reports have two fixes. They now separate a block your node refused from '
  + 'one that simply lost a race to another block at the same height, which mean very '
  + 'different things and used to be counted together. And a report no longer fails on a '
  + 'busy miner: one tester with a lot of rejected shares got an error instead of a report. '
  + 'Nothing you have set is changed by this update.'

export const current = VersionInfo.of({
  version: '1.0.0:26',
  releaseNotes: {
    en_US: notes,
    es_ES: notes,
    de_DE: notes,
    pl_PL: notes,
    fr_FR: notes,
  },
  migrations: {
    // Nothing to migrate. The store gained a `config` object and an
    // `adminPassword`, and every field carries a `.catch()` default, so an
    // existing store.json reads as all-unset and the gateway keeps its current
    // behaviour. Unset means the key is not written at all, which is how a
    // setting nobody has touched still gets DATUM's own default rather than
    // one we chose on their behalf.
    //
    // The dashboard password is generated by `seedFiles` on every init when the
    // field is absent, so an existing install picks one up on this update and
    // the admin pages work without the user doing anything. The Dashboard
    // Password action is where they read it. Someone who clears it deliberately
    // keeps it cleared: an empty string is a decision, and only an absent field
    // is filled.
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
