import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'
import { storeJson } from '../fileModels/store.json'
import { chainFromAddress } from '../payoutAddress'

const notes =
  'Mines the BLAKE2b chain on mainnet. The proof of work changed there at block ' +
  '961640 on 30 August 2026, and the node package can now follow it, so this ' +
  'follows it too. The chain is still read from your node rather than set here. ' +
  ' ' +
  'The payout address is now kept per chain, and a mainnet address can be set. ' +
  'There used to be one address for the whole service, so pointing the node at ' +
  "another chain left the previous chain's address in place, and that address " +
  'belongs to a wallet the new chain never opens. It fails quietly: DATUM does ' +
  'not check which network an address came from, so a leftover test address on ' +
  'mainnet builds a perfectly valid payment to a key you may not hold. Set ' +
  'Payout Address now checks what you enter against the chain your node is on. ' +
  'An address you had set is moved to the chain its own prefix identifies; one ' +
  'that could belong to either test chain is left unassigned and you are asked, ' +
  'because guessing costs real money. ' +
  ' ' +
  'The Primary Coinbase Tag is now yours to set. It was locked to the value the ' +
  'chain requires at its activation block, which is consensus for exactly one ' +
  'block and free text everywhere else, so on mainnet it is simply a label for ' +
  'blocks you find. Leave it blank and the old behaviour is unchanged. If your ' +
  'node has not yet reached the activation height, the required value is added ' +
  'to whatever you choose rather than either being dropped. ' +
  ' ' +
  'On deployments without a settings form, such as Umbrel and plain Docker, the ' +
  'page this gateway serves now offers mainnet and lets you choose whether the ' +
  'node keeps the whole chain or only recent blocks. It is the whole settings ' +
  'interface there, so a control missing from it is a control you do not have. ' +
  ' ' +
  'Stopping the service is now clean. It was being asked to stop and then killed ' +
  'a few milliseconds later, before it could exit properly. ' +
  ' ' +
  'A confusing failure is explained rather than reported as a broken node. When ' +
  'a private chain has mined past its last halving the block subsidy reaches ' +
  'zero, so there is nothing to mine for; the gateway used to sit on ' +
  '"Initialising..." with no reason given. It now names the cause and says what ' +
  'to do. ' +
  ' ' +
  'The service is now called "Datum Gateway (BLAKE2b) Companion", matching the ' +
  '"Companion" naming on the nodes it runs against and marking it as ours rather than ' +
  'an official package. Only the display name changed.'

export const current = VersionInfo.of({
  version: '1.0.0:36',
  releaseNotes: {
    en_US: notes,
    es_ES: notes,
    de_DE: notes,
    pl_PL: notes,
    fr_FR: notes,
  },
  migrations: {
    // Nothing to migrate. The store gained a `config` object and an
    // `adminPassword`, and every field carries a `.catch()` default, so an
    // existing store.json reads as all-unset and the gateway keeps its current
    // behaviour. Unset means the key is not written at all, which is how a
    // setting nobody has touched still gets DATUM's own default rather than
    // one we chose on their behalf.
    //
    // The dashboard password is generated by `seedFiles` on every init when the
    // field is absent, so an existing install picks one up on this update and
    // the admin pages work without the user doing anything. The Dashboard
    // Password action is where they read it. Someone who clears it deliberately
    // keeps it cleared: an empty string is a decision, and only an absent field
    // is filled.
    up: async ({ effects }) => {
      // Move a pre-split payout address under the chain it belongs to.
      //
      // The old field recorded no chain, so the address itself is the only
      // evidence. `chainFromAddress` reads the prefix and answers null when the
      // prefix cannot decide, which is the honest answer for base58 test
      // addresses: regtest and the public test network share `m`, `n` and `2`,
      // and that shared prefix is precisely why a stale address was accepted on
      // the wrong chain instead of rejected.
      //
      // Undecidable means leave it unassigned. The critical task then asks for
      // one, which is a small interruption next to paying block rewards into a
      // wallet the operator may not have.
      const store = await storeJson.read().once()
      const legacy = store?.poolAddress?.trim()
      if (!legacy) return
      if (Object.keys(store?.poolAddresses ?? {}).length > 0) return

      const chain = chainFromAddress(legacy)
      if (!chain) return

      await storeJson.merge(effects, { poolAddresses: { [chain]: legacy } })
    },
    down: IMPOSSIBLE,
  },
})
